import type { Config } from 'tailwindcss';

const config: Config = {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: ['class', '[data-theme="dark"]'],
  theme: {
    extend: {
      colors: {
        bg: {
          primary: 'var(--color-bg-primary)',
          secondary: 'var(--color-bg-secondary)',
          card: 'var(--color-bg-card)',
          'card-hover': 'var(--color-bg-card-hover)',
          overlay: 'var(--color-bg-overlay)',
          input: 'var(--color-bg-input)',
          'input-focus': 'var(--color-bg-input-focus)',
          nav: 'var(--color-bg-nav)',
        },
        text: {
          primary: 'var(--color-text-primary)',
          secondary: 'var(--color-text-secondary)',
          placeholder: 'var(--color-text-placeholder)',
          'on-cta': 'var(--color-text-on-cta)',
          muted: 'var(--color-text-muted)',
          link: 'var(--color-text-link)',
        },
        accent: {
          warm: 'var(--color-accent-warm)',
          'warm-dark': 'var(--color-accent-warm-dark)',
          rose: 'var(--color-accent-rose)',
          sage: 'var(--color-accent-sage)',
          lavender: 'var(--color-accent-lavender)',
        },
        border: {
          subtle: 'var(--color-border-subtle)',
          medium: 'var(--color-border-medium)',
          focus: 'var(--color-border-focus)',
          'card-hover': 'var(--color-border-card-hover)',
          sage: 'var(--color-border-sage)',
        },
        surface: {
          storm: 'var(--color-surface-storm)',
          deep: 'var(--color-surface-deep)',
        },
        emotion: {
          angry: 'var(--color-emotion-angry)',
          sad: 'var(--color-emotion-sad)',
          anxious: 'var(--color-emotion-anxious)',
          numb: 'var(--color-emotion-numb)',
          calm: 'var(--color-emotion-calm)',
          joy: 'var(--color-emotion-joy)',
          overwhelmed: 'var(--color-emotion-overwhelmed)',
          exhausted: 'var(--color-emotion-exhausted)',
          frustrated: 'var(--color-emotion-frustrated)',
          confused: 'var(--color-emotion-confused)',
          hopeful: 'var(--color-emotion-hopeful)',
          lonely: 'var(--color-emotion-lonely)',
          stressed: 'var(--color-emotion-stressed)',
          lost: 'var(--color-emotion-lost)',
          grateful: 'var(--color-emotion-grateful)',
          proud: 'var(--color-emotion-proud)',
          insecure: 'var(--color-emotion-insecure)',
          excited: 'var(--color-emotion-excited)',
          restless: 'var(--color-emotion-restless)',
          panicked: 'var(--color-emotion-panicked)',
          inspired: 'var(--color-emotion-inspired)',
          loved: 'var(--color-emotion-loved)',
          peaceful: 'var(--color-emotion-peaceful)',
          passionate: 'var(--color-emotion-passionate)',
          empowered: 'var(--color-emotion-empowered)',
          euphoric: 'var(--color-emotion-euphoric)',
        },
        semantic: {
          success: 'var(--color-success)',
          'success-bg': 'var(--color-success-bg)',
          warning: 'var(--color-warning)',
          'warning-bg': 'var(--color-warning-bg)',
          error: 'var(--color-error)',
          'error-bg': 'var(--color-error-bg)',
          crisis: 'var(--color-crisis)',
          'crisis-bg': 'var(--color-crisis-bg)',
        },
      },
      fontFamily: {
        display: ["'Instrument Serif'", 'Georgia', 'serif'],
        body: ["'Inter'", 'system-ui', '-apple-system', 'sans-serif'],
        mono: ["'JetBrains Mono'", "'Fira Code'", 'monospace'],
      },
      fontSize: {
        '3xs': '0.563rem',
        '2xs': '0.688rem',
        xs: '0.750rem',
        sm: '0.875rem',
        base: '1.000rem',
        md: '1.125rem',
        lg: '1.333rem',
        xl: '1.500rem',
        '2xl': '2.250rem',
        '3xl': '3.000rem',
      },
      lineHeight: {
        tight: '1.25',
        snug: '1.375',
        normal: '1.5',
        relaxed: '1.625',
        loose: '1.75',
      },
      fontWeight: {
        regular: '400',
        medium: '500',
        semibold: '600',
        bold: '700',
      },
      letterSpacing: {
        tight: '-0.02em',
        normal: '0em',
        wide: '+0.05em',
        wider: '+0.10em',
        widest: '+0.15em',
      },
      spacing: {
        '2xs': '4px',
        xs: '8px',
        sm: '16px',
        md: '24px',
        lg: '32px',
        xl: '48px',
        '2xl': '64px',
        '3xl': '96px',
        '4xl': '128px',
      },
      borderRadius: {
        xs: '4px',
        sm: '8px',
        md: '12px',
        lg: '20px',
        xl: '24px',
        '2xl': '32px',
        full: '9999px',
      },
      boxShadow: {
        xs: '0 2px 8px rgba(0, 0, 0, 0.15)',
        sm: '0 4px 16px rgba(0, 0, 0, 0.20)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
        xl: 'var(--shadow-xl)',
        inset: 'inset 0 1px 0 rgba(255, 255, 255, 0.03)',
        'inset-md': 'inset 0 2px 8px rgba(0, 0, 0, 0.20)',
        'cta-default': 'var(--shadow-cta-default)',
        'cta-hover': 'var(--shadow-cta-hover)',
        'cta-rant': 'var(--shadow-cta-rant)',
      },
      maxWidth: {
        page: '1200px',
        content: '720px',
        narrow: '520px',
        text: '65ch',
      },
      zIndex: {
        below: '-1',
        base: '0',
        raised: '10',
        dropdown: '100',
        sticky: '200',
        overlay: '300',
        modal: '400',
        toast: '500',
        crisis: '999',
        texture: '9999',
      },
      transitionTimingFunction: {
        comfort: 'cubic-bezier(0.25, 0.46, 0.45, 0.94)',
        settle: 'cubic-bezier(0.34, 1.56, 0.64, 1)',
        release: 'cubic-bezier(0.55, 0.06, 0.68, 0.19)',
        breathe: 'cubic-bezier(0.37, 0.00, 0.63, 1.00)',
        standard: 'cubic-bezier(0.20, 0.00, 0.00, 1.00)',
      },
      transitionDuration: {
        micro: '200ms',
        small: '350ms',
        medium: '500ms',
        large: '700ms',
        ambient: '8000ms',
        dissolve: '3000ms',
      },
      screens: {
        'mobile-s': '320px',
        'mobile-l': '480px',
        tablet: '768px',
        desktop: '1024px',
        'desktop-l': '1280px',
        ultrawide: '1536px',
      },
      keyframes: {
        pulseGlow: {
          '0%, 100%': { filter: 'blur(8px)' },
          '50%': { filter: 'blur(16px)' },
        },
        breathingCycle: {
          '0%': { transform: 'scale(1.00)', opacity: '0.60' },
          '21%': { transform: 'scale(1.60)', opacity: '1.00' },
          '58%': { transform: 'scale(1.60)', opacity: '1.00' },
          '100%': { transform: 'scale(1.00)', opacity: '0.60' },
        },
        skeletonShimmer: {
          '0%': { backgroundPosition: '200% 0' },
          '100%': { backgroundPosition: '-200% 0' },
        },
        spin: {
          to: { transform: 'rotate(360deg)' },
        },
        fadeUp: {
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        orbPulse: {
          '0%, 100%': { boxShadow: '0 0 8px rgba(133, 183, 157, 0.15)' },
          '50%': { boxShadow: '0 0 24px rgba(133, 183, 157, 0.35)' },
        },
        breatheOrb1: {
          '0%, 100%': { transform: 'scale(1.00) translate(0, 0)', opacity: '0.10' },
          '50%': { transform: 'scale(1.15) translate(30px, -20px)', opacity: '0.18' },
        },
        breatheOrb2: {
          '0%, 100%': { transform: 'scale(1.00) translate(0, 0)', opacity: '0.08' },
          '50%': { transform: 'scale(1.20) translate(-20px, 30px)', opacity: '0.16' },
        },
        borderPulse: {
          '0%, 100%': { borderColor: 'rgba(240, 230, 211, 0.08)' },
          '50%': { borderColor: 'rgba(133, 183, 157, 0.25)' },
        },
        wordDrift: {
          '0%': { transform: 'translateY(0) translateX(0)' },
          '25%': { transform: 'translateY(-8px) translateX(4px)' },
          '50%': { transform: 'translateY(-4px) translateX(-6px)' },
          '75%': { transform: 'translateY(-12px) translateX(3px)' },
          '100%': { transform: 'translateY(0) translateX(0)' },
        },
      },
      animation: {
        'pulse-glow': 'pulseGlow 2s cubic-bezier(0.37, 0, 0.63, 1) infinite',
        'breathing-cycle': 'breathingCycle 19s cubic-bezier(0.37, 0, 0.63, 1) infinite',
        'skeleton-shimmer': 'skeletonShimmer 1.5s ease infinite',
        spin: 'spin 0.6s linear infinite',
        'fade-up': 'fadeUp 700ms cubic-bezier(0.34, 1.56, 0.64, 1) forwards',
        'orb-pulse': 'orbPulse 3s cubic-bezier(0.37, 0, 0.63, 1) infinite',
        'breathe-orb-1': 'breatheOrb1 8s cubic-bezier(0.37, 0, 0.63, 1) infinite',
        'breathe-orb-2': 'breatheOrb2 8s cubic-bezier(0.37, 0, 0.63, 1) infinite',
        'border-pulse': 'borderPulse 4s cubic-bezier(0.37, 0, 0.63, 1) infinite',
        'word-drift': 'wordDrift linear infinite',
      },
    },
  },
  plugins: [],
};

export default config;
